### PR TITLE
Finish homepage redesign

### PR DESCRIPTION
**Pull request by viviangb**

### CODE REVIEW

**Comment by viviangb** [comment]
This is the redesign based on Alice Perez mockups.

**Comment by travm** [comment]
screen shot 2016-10-13 at 3 55 45 pm

I'm thinking we should add some space around the top nav on smaller browser widths to give it a bit more room to breathe. Thoughts?

**Comment by phated** [comment]
👍  on that.  I've still not done a review on this, so good insights!

**Comment by viviangb** [comment]
Do you guys need more info to accept this?

**Comment by phated** [comment]
We need to do a more thorough review and remove a bunch of the commits that diverged.  I haven't had time to look at this, sorry.

**Comment by bdougie** [comment]
May I suggest using Netlify, they have a free plan [for all open source projects](https://www.netlify.com/open-source/) that provides great features, like [deploy previews](https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/), and [smart redirects](https://www.netlify.com/docs/redirects/). If you have any interest in trying it doesn't require anything except connecting an open source repo.
 
Feel free to test it out [here](https://app.netlify.com/signup)

**Comment by contra** [comment]
Seeing as this PR stalled, I might take a swing at doing a new pass at the site

**Comment by phated** [comment]
@viviangb Sorry that this stalled.  Sometimes simplicity trumps everything else.  We can incrementally add to the base version @contra created for which I've opened a bunch of issues.

**Pull request closed without merging**
