### PR TITLE
Fix Hero Svg

### PR DESCRIPTION
**Pull request by jagdish7908**
### Fixed Hero svg paths

**1. Overlapping joint**
image

**2. Joint not aligned**
image

### CODE REVIEW

**Comment by phated** [comment]
Can you include a screenshot of your changes?

**Comment by jagdish7908** [comment]
@phated 
Screenshot of changes
image

**Comment by jagdish7908** [comment]
@phated are there any other comments or we can close this PR?

**Comment by phated** [comment]
Thanks for the reminder! This looks good. Thank you!

**Pull request merged**
