### PR TITLE
Issue # 39

### PR DESCRIPTION
**Pull request by dantesolis**
Hey guys here is some work on the header and the feature section of the new site. Let me know what you guys think.

Ref [issue#39](https://github.com/gulpjs/gulpjs.github.io/issues/39)

Screenshoots

**MOBILE**
mobile-feature
mobile-footer
mobile-header

**WEB**

web-feature
web-header

### CODE REVIEW

**Comment by phated** [comment]
At first glance, I don't think these changes are needed. The command line image is important to have above the fold and looks really nice.

**Comment by dantesolis** [comment]
@phated I was basing myself from the [marvel mockup](https://marvelapp.com/gj54hh/screen/14587285) should I change/remove: add something. I'm working on the other sections

**Comment by phated** [comment]
That mockup is just a reference point, the design has been altered since contra's redesign.

**Comment by dantesolis** [comment]
@phated Is there any other mockup i could use as reference?  Still interested in contributing.

**Comment by contra** [comment]
@dantesolis Not sure if the site needs much right now, keep your eye on the issues list though and feel free to jump in on any problems people post

**Pull request closed without merging**
