### PR TITLE
Add favicon

### PR DESCRIPTION
**Pull request by alexandernanberg**

### CODE REVIEW

**Comment by phated** [comment]
My browser has a favicon but maybe it's leftover from the old site.  We should use the same one (minus the small white line underneath).
screen shot 2017-03-22 at 1 56 31 pm

**Comment by alexandernanberg** [comment]
Yea probably a left over, browsers tend to cache favicons pretty hard. Personally I think the other one looks better, but sure I'll change it to the text logo

**Comment by phated** [comment]
I like the text more. @contra which one do you like?

**Comment by alexandernanberg** [comment]
Changed my mind, prefer this one now
image

**Comment by contra** [comment]
Text is better

**Comment by alexandernanberg** [comment]
Updated with text favicon

**Pull request merged**
